@startuml
title MVP Context Diagram for call center task

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(call_center_employee, "Сотрудник кол-центра")
Person_Ext(partner_call_center_employee, "Сотрудник партнерского кол-центра")
System(deposit_system, "Система по работе с депозитами")
System(call_center, "Система кол-центра")
System(sftp_server, "SFTP-сервер")
System_Ext(partner_call_center, "Партнерский кол-центр")

Rel(deposit_system, call_center, "UC1")
Rel(call_center, deposit_system, "UC1")
Rel(call_center_employee, call_center, "UC2")
Rel(deposit_system, sftp_server, "UC3")
Rel(partner_call_center, sftp_server, "Получение файла")
Rel(partner_call_center_employee, partner_call_center, "Работа с заявками")

@enduml