@startuml
title MVP Container Diagram for call center task

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(call_center_employee, "Сотрудник кол-центра")
Person_Ext(partner_call_center_employee, "Сотрудник партнерского кол-центра")
System(deposit_system, "Система по работе с депозитами")
System(call_center_system, "Система кол-центра")
System(sftp_server, "SFTP-сервер")
System_Ext(partner_call_center, "Партнерский кол-центр")

Container_Boundary(call_center_system, "Система кол-центра") {
  Container(call_center_system_front, "Веб-интерфейс кол-центра", "React.js")
  Container(call_center_system_back, "Бэкенд кол-центра", "Java Spring Boot")
  ContainerDb(call_center_system_db, "База данных кол-центра", "PostgreSQL")
}
Container_Boundary(deposit_system, "Система по работе с депозитами") {
  Container(deposit_system_front, "Веб-интерфейс системы по работе с депозитами", "React.js")
  Container(deposit_system_back, "Бэкенд системы по работе с депозитами", "Java Spring Boot")
  ContainerDb(deposit_system_db, "База данных системы по работе с депозитами", "PostgreSQL")
}


Rel(call_center_employee, call_center_system_front, "UC2")
Rel(call_center_system_front, call_center_system_back, "Обработка данных")
Rel(call_center_system_back, call_center_system_db, "Работа с данными")
Rel(call_center_system_back, deposit_system_back, "UC1")
Rel(deposit_system_back, call_center_system_back, "UC1")
Rel(deposit_system_front, deposit_system_back, "Обработка данных")
Rel(deposit_system_back, deposit_system_db, "Работа с данными")
Rel(deposit_system_back, sftp_server, "UC3")
Rel(partner_call_center, sftp_server, "Получение файла")
Rel(partner_call_center_employee, partner_call_center, "Работа с заявками")


@enduml